### ISSUE TITLE
Switching board from the side menu does not update card titles

### ISSUE THREAD

**Issue by bali182** [Madmous/madClones#6]
Hey, just experimented a bit with the demo and found this. Steps to repro

1. Created a new board called `froggo`
2. Opened it, added 2 cards with 1-1 sub-items - refreshed the board to make the cards appear (same issue as #3) after the cards and items were created.
3. Opened board called `Hello world`
4. Card titles on the first 2 cards were from my freshly created cards.

**Comment by Madmous** [comment]
Thanks for the bug report.
It might have been fix with but if not I make sure the next release fixes it.
